version: '2'
services:
  dev_piglegweb:
    image: "dev_piglegweb:latest"
    build: ./docker
    ports:
      - '${PIGLEG_PORT}:8000'
      # outer:inner
    environment:
      - PIGLEGCV_HOSTNAME=dev_piglegcv
      - PIGLEGCV_PORT=5000
      - PIGLEGCV_HOSTNAME_DEVEL=piglegcv_devel
      - PIGLEGCV_PORT_DEVEL=5000
    env_file:
      - ".env.dev"
#      - DOCKERLOGNAME="devel"
#     dockery vidí své vnitřní porty, nikoliv ty vnější
    volumes:
      - "${PIGLEG_ROOT_DIR}:/webapps/piglegsurgery"
      - "${PIGLEG_MEDIA_DIR}:/webapps/piglegsurgery/piglegsurgeryweb/media"
      - "${PIGLEG_LOG_DIR}:/root/pigleg/logs"
      #      - "C:/Users/Jirik/projects/piglegsurgery:/webapps/piglegsurgery"
  dev_piglegcv:
    image: "dev_piglegcv:latest"
    build: ./piglegcv
    env_file:
      - ".env.dev"
#    command: nvidia-smi
#    runtime: nvidia
    ports:
      - '5000'
      - '8808:8888'
      # outer:inner
#    environment:
#      - DOCKERLOGNAME=""
    volumes:
      # outer:inner
      - "${PIGLEG_ROOT_DIR}:/webapps/piglegsurgery"
      - '${PIGLEG_MEDIA_DIR}:/webapps/piglegsurgery/piglegsurgeryweb/media'
      - "${PIGLEG_LOG_DIR}:/home/appuser/logs"
      - "${PIGLEG_NBCONFIG_DIR}:/root/.jupyter"
      
volumes:
  dev_piglegweb:
    driver: local
  dev_piglegcv:
    driver: local
