version: '2'
services:
  dev_piglegweb:
    container_name: "${PIGLEG_IMAGE_PREFIX}piglegweb"
    image: "${PIGLEG_IMAGE_PREFIX}piglegweb:latest"
    ports:
      - '${PIGLEG_PORT}:8000'
      # outer:inner
    environment:
      - PIGLEGCV_HOSTNAME=dev_piglegcv
      - PIGLEGCV_PORT=5000
    #      - PIGLEGCV_HOSTNAME_DEVEL=piglegcv_devel
    #      - PIGLEGCV_PORT_DEVEL=5000
    #      - DOCKERLOGNAME="devel"
    #     dockery vidí své vnitřní porty, nikoliv ty vnější
    volumes:
      - "${PIGLEG_ROOT_DIR}:/webapps/piglegsurgery"
      - "${PIGLEG_MEDIA_DIR}:/webapps/piglegsurgery/piglegsurgeryweb/media"
      - "${PIGLEG_LOG_DIR}:/root/pigleg/logs"
      #      - "C:/Users/Jirik/projects/piglegsurgery:/webapps/piglegsurgery"
    networks:
      - dev_piglegnet
  dev_piglegcv:
    container_name: "${PIGLEG_IMAGE_PREFIX}piglegcv"
    image: "${PIGLEG_IMAGE_PREFIX}piglegcv:latest"
    build: piglegcv
    #    command: nvidia-smi
    #    runtime: nvidia
    ports:
      - '5000'
        # - '8888:8888'
        #- '8808:8888'
      - '${PIGLEG_JUPYTER_PORT}:8888'
    #    environment:
    #      - DOCKERLOGNAME=""
    volumes:
      - "${PIGLEG_ROOT_DIR}:/webapps/piglegsurgery"
      - '${PIGLEG_MEDIA_DIR}:/webapps/piglegsurgery/piglegsurgeryweb/media'
      - "${PIGLEG_LOG_DIR}:/home/appuser/logs"
      - "./.jupyter:/root/.jupyter"
    networks:
      - dev_piglegnet

#  redis:
#    image: redis:7.0.11-alpine
#    container_name: redis
#    restart: always
#    expose:
#      - 6379
#    command: >
#      --loglevel warning
##      --requirepass password
#    volumes:
#      - redis-data:/data:Z
volumes:
  dev_piglegweb:
    driver: local
  dev_piglegcv:
    driver: local

networks:
  dev_piglegnet:
