version: '3.8'
services:
  piglegweb:
    container_name: "${PIGLEG_IMAGE_PREFIX}piglegweb"
    image: "${PIGLEG_IMAGE_PREFIX}piglegweb:latest"
    build:
      context: ./docker
    ports:
      - '${PIGLEG_PORT}:8000'
      # outer:inner
    environment:
      - PIGLEGCV_HOSTNAME=piglegcv
      - PIGLEGCV_PORT=5000
      - PIGLEG_SPREADSHEET_URL="${PIGLEG_SPREADSHEET_URL}"
    env_file:
      - ".env.prod"
#     dockery vidí své vnitřní porty, nikoliv ty vnější
    volumes:
      - "${PIGLEG_ROOT_DIR}:/webapps/piglegsurgery"
      - "${PIGLEG_MEDIA_DIR}:/webapps/piglegsurgery/piglegsurgeryweb/media"
      - "${PIGLEG_LOG_DIR}:/root/pigleg/logs"
      #      - "C:/Users/Jirik/projects/piglegsurgery:/webapps/piglegsurgery"
    networks:
      - piglegnet

  piglegcv:
    container_name: "${PIGLEG_IMAGE_PREFIX}piglegcv"
    image: "${PIGLEG_IMAGE_PREFIX}piglegcv:latest"
    build:
      context: ./piglegcv
    env_file:
      # there should be PIGLEG_DEVICE
      - ".env.prod"
    ports:
      - '5000'
      - '${PIGLEG_JUPYTER_PORT}:8888'
    volumes:
      - "${PIGLEG_ROOT_DIR}:/webapps/piglegsurgery"
      - "${PIGLEG_MEDIA_DIR}:/webapps/piglegsurgery/piglegsurgeryweb/media"
      - "${PIGLEG_LOG_DIR}:/home/appuser/logs"
      - "./.jupyter:/root/.jupyter"
    networks:
      - piglegnet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]
volumes:
  piglegweb:
    driver: local
  piglegcv:
    driver: local

networks:
  piglegnet:
