version: '2'
services:
#  mariadb:
#    image: docker.io/bitnami/mariadb:10.3
#    environment:
#      # ALLOW_EMPTY_PASSWORD is recommended only for development.
#      - ALLOW_EMPTY_PASSWORD=yes
#      - MARIADB_USER=bn_moodle
#      - MARIADB_DATABASE=bitnami_moodle
#      - MARIADB_CHARACTER_SET=utf8mb4
#      - MARIADB_COLLATE=utf8mb4_unicode_ci
#    volumes:
#      - 'mariadb_data:/bitnami/mariadb'
#  moodle:
#    image: docker.io/bitnami/moodle:3
#    ports:
#      - '88:8080'
#      - '443:8443'
#    environment:
#      - MOODLE_DATABASE_HOST=mariadb
#      - MOODLE_DATABASE_PORT_NUMBER=3306
#      - MOODLE_DATABASE_USER=bn_moodle
#      - MOODLE_DATABASE_NAME=bitnami_moodle
#      # ALLOW_EMPTY_PASSWORD is recommended only for development.
#      - ALLOW_EMPTY_PASSWORD=yes
#    volumes:
#      - 'moodle_data:/bitnami/moodle'
#      - 'moodledata_data:/bitnami/moodledata'
#    depends_on:
#      - mariadb
  piglegweb:
    image: piglegweb:latest
    ports:
      - '8000:${PIGLEG_PORT}'
    environment:
      - PIGLEGCV_HOSTNAME=piglegcv
      - PIGLEGCV_PORT=5000
      - PIGLEGCV_HOSTNAME_DEVEL=piglegcv_devel
      - PIGLEGCV_PORT_DEVEL=5000
#      - DOCKERLOGNAME="devel"
#     dockery vidí své vnitřní porty, nikoliv ty vnější
    volumes:
      - "${PIGLEG_ROOT_DIR}:/webapps/piglegsurgery"
      - "${PIGLEG_MEDIA_DIR}:/webapps/piglegsurgery/piglegsurgeryweb/media"
      - "${PIGLEG_LOG_DIR}:/root/pigleg/logs"
      #      - "C:/Users/Jirik/projects/piglegsurgery:/webapps/piglegsurgery"
  piglegcv:
    image: piglegcv:latest
#    command: nvidia-smi
#    runtime: nvidia
    ports:
      - '5000:5000'
#    environment:
#      - DOCKERLOGNAME=""
    volumes:
      - "${PIGLEG_ROOT_DIR}:/webapps/piglegsurgery"
      - '${PIGLEG_MEDIA_DIR}:/webapps/piglegsurgery/piglegsurgeryweb/media'
      - "${PIGLEG_LOG_DIR}:/home/appuser/logs"
      
  piglegcv_devel:
    privileged: true
    image: piglegcv_devel:latest
#    command: nvidia-smi
#    runtime: nvidia
    ports:
      - '5001:5000'
    environment:
      - DOCKERLOGNAME=devel
    volumes:
      - "${PIGLEG_ROOT_DIR}:/webapps/piglegsurgery"
      - '${PIGLEG_MEDIA_DIR}:/webapps/piglegsurgery/piglegsurgeryweb/media'
      - "${PIGLEG_LOG_DIR}:/home/appuser/logs"

#      - "C:/Users/Jirik/projects/piglegsurgery:/webapps/piglegsurgery"
#  piglegcv_devel:
#    image: piglegcv:latest
#    ports:
#      - '5000:5001'
#    volumes:
#      - "/webapps/piglegsurgery:/webapps/piglegsurgery"
##      - "C:/Users/Jirik/projects/piglegsurgery:/webapps/piglegsurgery"
volumes:
#  mariadb_data:
#    driver: local
#  moodle_data:
#    driver: local
#  moodledata_data:
#    driver: local
  piglegweb:
    driver: local
  piglegcv:
    driver: local
