name: piglegsurgery
channels:
#    - mjirik
#    - SimpleITK
    - conda-forge
    - anaconda
#    - pytorch
    - defaults
dependencies:
    - python
    - pip
    - django
    - django-allauth
    - redis
#    - openslide
    - pandas>=1.1
    - google-api-python-client
    - google-auth-httplib2
    - google-auth
    # maybe not necessary
    - google-auth-oauthlib
    - loguru
    - gunicorn
#    - scikit-image
#    - scipy
#    - io3d
#    - sed3
#    - seaborn
#    - pytz
#    - SimpleITK
#    - python-dateutil
#    - pytest
#    - pytorch=1.8.0
#    - torchvision
#    - torchaudio
#    - cudatoolkit=11.0
#    - scikit-learn
#    - timm

