name: piglegsurgery
channels:
#    - mjirik
#    - SimpleITK
    - conda-forge
    - anaconda
#    - pytorch
    - defaults
dependencies:
    - python=3.9
    - pip
    - django=3
    - django-allauth
    - django-environ
    - redis=3
#    - openslide
    - pandas=1.3
    - google-api-python-client
    - google-auth-httplib2
    - google-auth
    - gspread
    - google-api-python-client
    - oauth2client
    # maybe not necessary
    - google-auth-oauthlib
    - loguru=0.5
    - gunicorn=20
    - opencv=4
    - ffmpeg
    - pillow
    - pytest
#    - scikit-image
#    - scipy
#    - io3d
#    - sed3
#    - seaborn
#    - pytz
#    - SimpleITK
#    - python-dateutil
#    - pytest
#    - pytorch=1.8.0
#    - torchvision
#    - torchaudio
#    - cudatoolkit=11.0
#    - scikit-learn
#    - timm

